apiVersion: v1
kind: Service
metadata:
  name: wisecow
  labels:
    app: wisecow
spec:
  selector:
    app: wisecow
  ports:
  - name: http
    port: 80          # Service port inside the cluster
    targetPort: 4499  # Container port where Wisecow runs
    nodePort: 30080   # External port on your node
  type: NodePort
