apiVersion: v1
kind: Service
metadata:
  name: wisecow
  labels:
    app: wisecow
spec:
  selector:
    app: wisecow
  ports:
  - name: http
    port: 80          # Service port exposed outside
    targetPort: 4499  # Container port
  type: LoadBalancer

